## BUILD (BACKEND, DB, FRONTEND)

version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=docker-reoit-ecommerce
      - MYSQL_ROOT_PASSWORD=Reo.2640441
    ports:
      - '3307:3306'
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
    expose:
      - 3306

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: backend
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - FRONTEND_CLIENT_URL=http://localhost
    ports:
      - 8080:8080
    expose:
      - 8080

  frontend:
    image: nginx:1.25.3 
    ports:
      - 80:80 ## port trai port mapping frontend , port phai port frontend docker
    volumes:
      - ../frontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      
## docker compose -p viettaiit up -d
## -p (project-name)
## -d (run on background) 