version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=docker-reoit-ecommerce
      - MYSQL_ROOT_PASSWORD=Reo.2640441
    ports:
      - '3307:3306'
